<h1 class="h1-page-title"><?= $this->pageTitle; ?></h1>
<div class="article">
    <h2>Basic Bar Chart : </h2>
    <div id="div-chart-1">
        
        <?
//        echo $this->layout()->headLink()->setStylesheet($this->css); ;//$this->css
        ?>
        <?= $this->barGraph ?>
        <?= $this->barGraph ?>
        <?= $this->barGraph ?>
    </div>
    <hr />
    <h2>Basic Line Chart : </h2>
    <div id="div-chart-2">
        
    </div>
    <hr />
</div>