<div class="article">
    <table style="display: none;">
        <tr>
            <td style="padding: 4px;">
                <img src="/img/icons_svg/task_icon.svg"
                     style="width: 32px;"  />
            </td>
            <td>
                <?= $this->translate('CREATE_NEW_PROJECT'); ?>
            </td>
            <td style="padding: 4px;">
                <img src="/img/icons_svg/project_icon.svg"
                     style="width: 32px;"  />
            </td>
            <td>
                <?= $this->translate('CREATE_NEW_TASK'); ?>
            </td>
        </tr>`
    </table>
</div>
<div class="article" style="border: 1px solid #ececec;">
    
    <div id="user-summary" 
         style="float: left; width: 32%; border-right: 1px solid #ececec;">
        <table>
            <tr>
                <td style="padding: 6px;">
                    <img src="/img/users/user.svg" style="width: 80px;" />
                </td>
                <td style="padding: 6px;">
                    <h3 class="h3-dashboard"
                        style="color: #D88E30;">USER_NAME</h3>
                    <div style="padding: 6px;">
                        hsqdghfqgqsg
                        <br />
                        kfqshgiduqfghq
                        <br />
                        fshjdsg
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div id="user-activity-summary" style="margin-left: 34%; padding: 6px;">
        <table>
            <tr>
                <td style="padding: 6px;">
                    <h3 class="h3-dashboard">LAST_ALERT :</h3>
                </td>
                <td style="padding: 6px;">
                    hsqdghfqgqsg kfqshgiduqfghq fshjdsg 
                    jsfqhgijg jsfqhdilgsdkfg 
                </td>
            </tr>
            <tr>
                <td style="padding: 6px;">
                    <h3 class="h3-dashboard">LAST_EDIT :</h3>
                </td>
                <td style="padding: 6px;">
                    hsqdghfqgqsg kfqshgiduqfghq fshjdsg jsfqhgijg jsfqhdilgsdkfg 
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="article" style="margin: 20px 0px; padding: 0px;">
    <div style="float: left; width: 32%; min-height: 300px; border: 1px solid #ececec;">
        <h3 class="h3-dashboard">ACTIVE_PROJECT :</h3>
        <ul class="ul-dashbord">
            <li>Project #NNN</li>
            <li>Project #NNN</li>
            <li>Project #NNN</li>
        </ul>
    </div>
    <div style="float: right; width: 32%; min-height: 300px; border: 1px solid #ececec;">
        <h3 class="h3-dashboard">INBOX :</h3>
        <ul class="ul-dashbord">
            <li>Alert ...</li>
            <li>Msg ...</li>
            <li>Alert ...</li>
            <li>Msg ...</li>
            <li>Alert ...</li>
            <li>Msg ...</li>
        </ul>
    </div>
    <div style="margin-left: 34%; margin-right: 34%; width: 32%; min-height: 300px; border: 1px solid #ececec;">
        <h3 class="h3-dashboard">ACTIVE_TASK :</h3>
        <ul class="ul-dashbord">
            <li>Task #NNN</li>
            <li>Task #NNN</li>
            <li>Task #NNN</li>
        </ul>
    </div>
</div>