<h1 class="h1-page-title"><?= $this->pageTitle; ?></h1>
<div class="article">
    <table style="display: none;">
        <tr>
            <td style="padding: 4px;">
                <img src="/img/icons_svg/task_icon.svg"
                     style="width: 32px;"  />
            </td>
            <td>
                <?= $this->translate('CREATE_NEW_PROJECT'); ?>
            </td>
            <td style="padding: 4px;">
                <img src="/img/icons_svg/project_icon.svg"
                     style="width: 32px;"  />
            </td>
            <td>
                <?= $this->translate('CREATE_NEW_TASK'); ?>
            </td>
        </tr>`
    </table>
</div>