<div style="margin: 20px 0px; padding: 0px;">
    <div id="user-summary">
        <table>
            <tr>
                <td style="padding: 6px;">
                    <img src="/img/users/g_user.svg" style="width: 80px;" />
                </td>
                <td style="padding: 6px;">
                    <h3 class="h3-dashboard">USER_NAME</h3>
                    <div style="padding: 6px;">
                        hsqdghfqgqsg
                        <br />
                        kfqshgiduqfghq
                        <br />
                        fshjdsg
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div id="user-activity-summary">
        <table>
            <tr>
                <td style="padding: 6px; text-align: right;">
                    <h3 class="h3-dashboard">LAST_ALERT :</h3>
                </td>
                <td style="padding: 6px;">
                    <?php
                    echo $this->lastAlert;
                    ?>
                </td>
            </tr>
            <tr>
                <td style="padding: 6px; text-align: right;">
                    <h3 class="h3-dashboard">LAST_EDIT :</h3>
                </td>
                <td style="padding: 6px;">
                    <?php
                    echo $this->lastAlert;
                    ?> 
                </td>
            </tr>
        </table>
    </div>
</div>
<div style="margin: 20px 0px; padding: 0px;">
    <div id="div-index-inbox-msg">
        <h3 class="h3-dashboard heading">INBOX :</h3>
        <ul class="ul-dashbord">
            <li>
                <span class="index-inbox-msg">Message ...</span>
                <span class="index-inbox-date">
                    <?= $this->lastAlert; ?>
                </span>
            </li>
            <li>
                <span class="index-inbox-msg">Message ...</span>
                <span class="index-inbox-date">
                    <?= $this->lastAlert; ?>
                </span>
            </li>
            <li>
                <span class="index-inbox-msg">Message ...</span>
                <span class="index-inbox-date">
                    <?= $this->lastAlert; ?>
                </span>
            </li>
            <li>
                <span class="index-inbox-msg">Message ...</span>
                <span class="index-inbox-date">
                    <?= $this->lastAlert; ?>
                </span>
            </li>
        </ul>
    </div>
    <div id="div-index-active-project">
        <h3 class="h3-dashboard heading">ACTIVE_PROJECT :</h3>
        <ul class="ul-dashbord">
            <li>Project #NNN</li>
            <li>Project #NNN</li>
            <li>Project #NNN</li>
        </ul>
    </div>
    <div id="div-index-active-task">
        <h3 class="h3-dashboard heading">ACTIVE_TASK :</h3>
        <ul class="ul-dashbord">
            <li>Task #NNN</li>
            <li>Task #NNN</li>
            <li>Task #NNN</li>
        </ul>
    </div>
</div>

<div class="article" style="border: 1px solid #ececec; box-shadow: 0px 0px 2px #757575">
    <table id="tb-index-bottom-links">
        <tr>
            <td class="td-index-bottom-link-a">
                <img src="/img/icons_svg/b_folder_icon.svg"
                     style="width: 48px;"  />
            </td>
            <td class="td-index-bottom-link-b" style="border-right: 1px solid #ccc;">
                <a class="add-links"
                   href="/project/project/0">
                    <?=$this->translate('CREATE_NEW_PROJECT');?>
                </a>
            </td>
            <td class="td-index-bottom-link-a">
                <img src="/img/icons_svg/b_task_icon.svg"
                     style="width: 48px;"  />
            </td>
            <td class="td-index-bottom-link-b" style="border-right: 1px solid #ccc;">
                <a class="add-links"
                   href="/task/task/0">
                    <?=$this->translate('CREATE_NEW_TASK');?>
                </a>
            </td>
            <td class="td-index-bottom-link-a">
                <img src="/img/icons_svg/note_icon.svg"
                     style="width: 48px;"  />
            </td>
            <td class="td-index-bottom-link-b" style="border-right: 1px solid #ccc;">
                <a class="add-links"
                   href="/note/0/0">
                    <?=$this->translate('ADD_A_NOTE');?>
                </a>
            </td>
            <td class="td-index-bottom-link-a">
                <img src="/img/icons_svg/alert_icon.svg"
                     style="width: 48px;"  />
            </td>
            <td class="td-index-bottom-link-b">
                <a class="add-links"
                   href="/notify/0/0">
                    <?=$this->translate('ALERT_TASK');?>
                </a>
            </td>
        </tr>
    </table>
</div>