<?php echo $this->doctype('HTML5') ?>
<html>
<head>
    <?php
    $this->headMeta()->setCharset('UTF-8');
    $this->headLink()->setStylesheet('/css/reset.css')
                     ->appendStylesheet('/css/default.css');
    $this->headScript()->setFile('/js/library/jquery-1.8.2.js')
                       ->appendFile('/js/library/jquery.balloon.min.js')
                       ->appendFile('/js/myJquery.js')
                       ->appendFile('/js/myd3/d3.v2.js');
    echo $this->headTitle('Stats | BUGS2ME | Créations 2C');
    echo $this->headMeta();
    echo $this->headLink();
    echo $this->headStyle();
    echo $this->headScript();
    ?>
    <style type="text/css">
        #div-chart-1 {
            text-align: center;
            font: 10px sans-serif;
        }
        .axis path,
        .axis line {
            fill: none;
            stroke: #696969;
            shape-rendering: crispEdges;
        }

        .bar {
            fill: steelblue;
        }

        .x.axis path {
            display: none;
        }
        /*
        */
    </style>
    <script>
        //$(document).ready(function(){

        //});
    </script>
</head>
<body>
    
    <div id="header">
        <div id="header-top">
            <h1 id="sitename">
                <a href="/index/index">BUGS ME | Créations 2C</a>
            </h1> 
        </div>
        <div id="nav">
            <div id="nav-content">
                <div id="user-links" class="balloon" title="balloon content">
                    <?php
                        $auth = Zend_Auth::getInstance();
                        $user = new Core_Model_User();
                        if ($auth->getStorage()->read($user)) {
                            echo ucfirst(
                                    $auth->getStorage()->read($user)->getName()
                                );
                        } else {
                            echo 'John DOE';
                        }
                    ?>
                    &nbsp;(user links)
                </div>
                <?php echo $this->navigation(); ?>
                <div class="clear-both"></div>
            </div>
        </div>
    </div>
    
    <div id="notification"></div>
    
    <div id="main">
        graph
        <br />
        <?php echo $this->layout()->content . PHP_EOL;?>
    </div>

    <div id="footer">
        <p style="margin-: auto; width: 1000px;">
             <img src="/img/creations2c.png" 
                  alt="Une création 2C" style="width: 90px;" />
             &nbsp;&nbsp;
             <img src="/img/PoweredBy_ZF_4LightBG.png" 
                  alt="Powered by Zend Framework" />
        </p>
    </div>
    <div id="popup">
        <div style="height: 500px">
            <h1 class="h1-page-title">HELP</h1>
            <p>
                CONTENT
                <br />
            </p>
            <p>
                <br />
                @TODO: Ajax Treatment...
            </p>
        </div>
        <div id="popup-close-btn">
            <a href="">CLOSE</a>
        </div>
    </div>
</body>
<?php
//echo $this->headScript()->setFile('/js/myPrototype.js') . PHP_EOL;
?>
</html>