<?php
//echo 'TASK ID    : ' . $this->taskId . '<br />';
//echo 'PROJECT ID : ' . $this->projectId . '<br />';
//echo $this->formTask . '<br />';

?>
<?php
$buttonDecorators = array(
    'ViewHelper',
    array(
        array(
            'row' => 'HtmlTag',
            'class' => 'sub'
        ),
        array(
            'tag'   => 'div',
            'class' => 'form-row-submit offset-label'
        )
    )
);
//$formTask = new Zend_Form();
//$formTask->sel_task_project->;
$this->formTask->inp_task_name
               ->setLabel('TASK_NAME');
$this->formTask->sel_task_project
               ->setLabel('PROJECT_NAME')
               ;
$this->formTask->inp_task_id
               ->setLabel('TASK_ID');
$this->formTask->inp_task_start_datepicker
               ->setLabel('TASK_START_DATE');
$this->formTask->inp_task_end_datepicker
               ->setLabel('TASK_END_DATE');
$this->formTask->sel_task_manager
               ->setLabel('TASK_MANAGER');
$this->formTask->sel_task_priority
               ->setLabel('TASK_PRIORITY');
$this->formTask->tarea_task_description
               ->setLabel('TASK_DESCRIPTION');

//if ($this->taskId === 0) {
    $this->formTask->submit_task_form->setLabel('SUBMIT')
                                     ->clearDecorators()
                                     ->setDecorators($buttonDecorators);
//}

//$this->formTask->setDecorators(
//        array(
//            'FormElements',
//            array( 'FormErrors', array(
//                'placement'       => 'prepend',
//                'markupListStart' => '<div class="alert-message info">',
//                'markupListEnd'   => '</div>'
//            ))
//        )
//    ); 
?>

<div class="div-time-elapsed-page-title">
    <?php
    //@TODO : elapsed time
    echo $this->translate('TASK_ELAPSED_TIME') . ' : ';
    echo '<span class="span-h1">';
    echo ($this->elapsed) ? $this->elapsed : '00:00:00';
    echo '</span>';
    ?>
</div>

<h1 class="h1-page-title"><?= $this->pageTitle; ?></h1>

<div class="action-content">
    
    <div><?= $this->formTask; ?></div>
    <br /><br />
    <?php if ($this->pid !== 0) : ?>
    <div class="div-task-notes">
        <h2 class="h2-task-notes">
            <?= $this->translate('NOTE_LIST_TITLE') ?>
        </h2>
        <ul class="ul-task-notes">
            <?php
            if ($this->notes) :
                foreach ($this->notes as $noteValue) :
            ?>
                <li class="li-task-note">
                    <a href=""><?= $noteValue ?></a>
                </li>
            <?php
                endforeach;
            else :
            ?>
                <li class="li-task-nonote">
                    No note
                </li>
            <?php
            endif;
            ?>
        </ul>
    </div>
    <?php endif; ?>
    
</div>

<!-- MENU //-->
<div class="article-btn">
    <ul class="ul-btn-add">
        <li>
            <table>
                <tr>
                    <td style="padding: 4px;">
                        <img src="/img/icons_svg/backward_icon.svg"
                             style="width: 32px;" />
                    </td>
                    <td style="padding: 4px;">
                        <a class="add-links"
                           href="/task/list">
                            <?=$this->translate('BACKWARD');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
        <li>
            <table>
                <tr>
                    <td style="padding: 4px;">
                        <img src="/img/icons_svg/help_icon.svg"
                             style="width: 32px;" />
                    </td>
                    <td style="padding: 4px;">
                        <a class="add-links"
                           href="javascript: return false;">
                            <?=$this->translate('HELP_TASK');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
    </ul>
    <div class="article">
        
    </div>
</div>