<table class="tb-to-task-links">
    <tr>
        <td class="td-to-task-link-a">
            <img src="/img/icons_svg/w_task_icon.svg"
                 style="width: 22px;"  />
        </td>
        <td class="td-to-task-link-b" style="font-size: 12px;">
            <a class="add-links"
               href="/task/task/0" style="color: #ffffff; font-size: 12px;">
                <?=$this->translate('CREATE_NEW_TASK');?>
            </a>
        </td>
    </tr>
</table>

<br />
<div class="article">
    <ul class="ul-tasks">
    <?php foreach ($this->tasks as $taskId => $taskValue) : ?>
        <li class="li-tasks">
        <?='<a href="/task/task/'.$taskId.'" 
                 id="a-task-'.$taskId.'">'.$taskValue.'</a>'?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>