<?php
$buttonDecorators = array(
    'ViewHelper',
    array(
        array(
            'row' => 'HtmlTag',
            'class' => 'sub'
        ),
        array(
            'tag'   => 'div',
            'class' => 'form-row-submit offset-label'
        )
    )
);

$this->formTask->inp_task_name->setLabel('TASK_NAME');
$this->formTask->sel_task_project->setLabel('PROJECT_NAME');
$this->formTask->inp_task_id->setLabel('TASK_ID');
$this->formTask->inp_task_start_datepicker->setLabel('TASK_START_DATE');
$this->formTask->inp_task_end_datepicker->setLabel('TASK_END_DATE');
$this->formTask->sel_task_manager->setLabel('TASK_MANAGER');
$this->formTask->sel_task_priority->setLabel('TASK_PRIORITY');
$this->formTask->tarea_task_description->setLabel('TASK_DESCRIPTION');

if ($this->taskId === 0) {
    $this->formTask->submit_task_form->setLabel('SUBMIT')
                                     ->clearDecorators()
                                     ->setDecorators($buttonDecorators);
} else {
    $this->formTask->removeElement('submit_task_form');
}
//$this->formTask->setDecorators(
//        array(
//            'FormElements',
//            array( 'FormErrors', array(
//                'placement'       => 'prepend',
//                'markupListStart' => '<div class="alert-message info">',
//                'markupListEnd'   => '</div>'
//            ))
//        )
//    ); 
?>

<div class="div-time-elapsed-page-title">
<?php
//@TODO : elapsed time
echo $this->translate('TASK_ELAPSED_TIME') . ' : ';
echo '<span class="span-h1">';
echo ($this->elapsed) ? $this->elapsed : '00:00:00';
echo '</span>';
?>
</div>

<h1 class="h1-page-title"><?= $this->pageTitle; ?></h1>

<div class="action-content">
<?= $this->formTask; ?>
</div>


<div class="article-btn">
    <ul class="ul-btn-add">
    <?php if ($this->userRole <= 3) : ?>
        
        <?php if ($this->taskId > 0) : ?>
        <li>
            <table class="table-ul-btn-add">
                <tr>
                    <td class="td-ul-btn-add-a">
                        <img src="/img/icons_svg/timer_icon.svg" />
                    </td>
                    <td class="td-ul-btn-add-b">
                        <a class="add-links" href="#<?=$this->taskId?>">
                        <?= $this->translate('ADD_TIME'); ?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
        <?php endif; ?>
        
        <?php
        //@TODO : Tempory treatment, refactor, move...
        $disabledNote = ($this->taskId === 0)
            ? 'javascript: var i = 0; return false;' 
            : '/note/'.$this->taskId.'/0';
        $disabledAttach = ($this->taskId === 0)
            ? 'javascript: var i = 0; return false;' 
            : '/attach/file/'.$this->taskId.'/0';
        ?>
        <li>
            <table class="table-ul-btn-add">
                <tr>
                    <td class="td-ul-btn-add-a">
                        <img src="/img/icons_svg/note_icon.svg"
 />
                    </td>
                    <td class="td-ul-btn-add-b">
                        <a class="add-links"
                           href="<?=$disabledNote?>">
                        <?= $this->translate('ADD_A_NOTE'); ?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
        
        <li>
            <table class="table-ul-btn-add">
                <tr>
                    <td class="td-ul-btn-add-a">
                        <img src="/img/attachment_0_blue.png" />
                    </td>
                    <td class="td-ul-btn-add-b">
                        <a class="add-links"
                           href="<?=$disabledAttach?>">
                            <?=$this->translate('ATTACH_A_DOCUMENT');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
    <?php endif; ?>
        
    <?php if ($this->taskId > 0) : ?>
        <li>
            <table class="table-ul-btn-add">
                <tr>
                    <td class="td-ul-btn-add-a">
                        <img src="/img/icons_svg/alert_icon.svg" />
                    </td>
                    <td class="td-ul-btn-add-b">
                        <a class="add-links"
                           href="/task/task/<?=$this->taskId?>/alert">
                            <?=$this->translate('ALERT_TASK');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
    <?php endif; ?>
        
    <?php if ($this->taskId > 0) : ?>
        <li>
            <table class="table-ul-btn-add">
                <tr>
                    <td class="td-ul-btn-add-a">
                        <img src="/img/icons_svg/modify_icon.svg" />
                    </td>
                    <td class="td-ul-btn-add-b">
                        <a class="add-links"
                           href="/task/task/<?=$this->taskId?>">
                            <?= $this->translate('MODIFY_TASK'); ?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
    
        <?php if ($this->userRole <= 2 && $this->taskId > 0) : ?>
        <li>
            <table class="table-ul-btn-add">
                <tr>
                    <td class="td-ul-btn-add-a">
                        <img src="/img/icons_svg/lock_icon.svg" />
                    </td>
                    <td class="td-ul-btn-add-b">
                        <a class="add-links"
                           href="/task/task/<?=$this->taskId?>/close">
                            <?=$this->translate('CLOSE_TASK');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
        <?php endif; ?>
    
    <?php endif; ?>
        <li>
            <table class="table-ul-btn-add">
                <tr>
                    <td class="td-ul-btn-add-a">
                        <img src="/img/icons_svg/help_icon.svg" />
                    </td>
                    <td class="td-ul-btn-add-b">
                        <a class="add-links"
                           href="javascript: return false;">
                            <?=$this->translate('HELP_TASK');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
    </ul>
    
    <?php if ($this->taskId == 0) : ?>
    <br />
    <div class="article">
        <p>TODO : Explain...</p>
    </div>
    <?php endif; ?>
</div>


