<?php
$fieldDecorators = array(
                        'ViewHelper',
                        array(
                            array('elt' => 'HtmlTag'),
                            array(
                                'tag'   => 'div',
                                'class' => 'form-div-elt',
                                'style' => 'display: inline;'
                            )
                        ),
                        array(
                            'Label',
                            array(
                                'class' => 'form-elt-label',
                                'style' => 'padding-right: 30px;'
                            ),
//                            array(
//                                'tag'   => 'div',
//                                'class' => 'form-div-label'
//                            )
                        ),
                        'Description',
                        'Errors',
                        array(
                            array('row' => 'HtmlTag'),
                            array(
                                'tag'   => 'div',
                                'class' => 'form-row'
                            )
                        )
                    );
$tareaDecorators = array(
                        'ViewHelper',
                        array(
                            array('elt' => 'HtmlTag'),
                            array(
                                'tag'   => 'div',
                                'class' => 'div-tarea'
                            )
                        ),
                        array(
                            'Label',
                            array('class' => 'form-elt-label'),
                        ),
                        'Description',
                        'Errors',
                        array(
                            array('row' => 'HtmlTag'),
                            array(
                                'tag'   => 'div',
                                'class' => 'form-row'
                            )
                        )
                    );

$buttonDecorators = array(
                        'ViewHelper',
                        array(
                            array(
                                'row' => 'HtmlTag',
                                'class' => 'sub'
                            ),
                            array(
                                'tag'   => 'div',
                                'class' => 'form-row-submit offset-label'
                            )
                        )
                    );

$this->formTask->inp_task_name->setLabel('TASK_NAME')
        ;
$this->formTask->inp_task_start_datepicker->setLabel('TASK_START_DATE');
$this->formTask->inp_task_end_datepicker->setLabel('TASK_END_DATE');
$this->formTask->sel_task_manager->setLabel('TASK_MANAGER');
$this->formTask->tarea_task_description->setLabel('TASK_DESCRIPTION');
$this->formTask->hid_task_id->clearDecorators()
                       ->setDecorators($buttonDecorators);
if ($this->taskId === 0) {
$this->formTask->submit_task_form->setLabel('SUBMIT')
                       ->clearDecorators()
                       ->setDecorators($buttonDecorators);
} else {
    $this->formTask->removeElement('submit_task_form');
}
?>

<div style="float:right; margin: 0; padding: 6px; line-height: 24px;">
    <?php
    //@TODO : elapsed time
        echo $this->translate('TASK_ELAPSED_TIME') . ' : ';
        echo '<span class="span-h1">';
        echo '00:00:00';
        echo '</span>';
    ?>
</div>
<h1 class="h1-page-title"><?= $this->pageTitle; ?></h1>
<div style="float:left; margin-top: 10px; padding: 0; width: 780px; border-right: 1px solid #ECECEC;">
    <?= $this->formTask; ?>
</div>

<?php if ($this->taskId > 0) : ?>
<div class="article-btn" style="margin-top: 30px; margin-left: 800px; ">
    <ul class="ul-btn-add">
        <li>
            <table>
                <tr>
                    <td style="padding: 4px;">
                        <img src="/img/add_note_0.jpeg" style="width: 24px;" />
                    </td>
                    <td style="padding: 4px;">
                        <a class="add-links" href="/task/task/<?=$this->taskId?>/0">
                            <?=$this->translate('ADD_A_NOTE');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
        <li>
            <table>
                <tr>
                    <td style="padding: 4px;">
                        <img src="/img/attachment_0.png" style="width: 24px;"  />
                    </td>
                    <td style="padding: 4px;">
                        <a class="add-links" href="/task/task/0/file">
                            <?=$this->translate('ATTACH_A_DOCUMENT');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
        <?php if (isset($this->userRole)) : ?>
        <li>
            <table>
                <tr>
                    <td style="padding: 4px;">
                        <!--<img src="/img/attachment_0.png" style="width: 24px;"  />-->
                    </td>
                    <td style="padding: 4px;">
                        <a class="add-links" href="/task/task/<?=$this->taskId?>">
                            <?=$this->translate('MODIFY_TASK');?>
                        </a>
                    </td>
                </tr>
            </table>
        </li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>
