<h1 class="h1-page-title"><?= $this->pageTitle; ?></h1>

<div class="article">
    <?php
    
    /*
    ?>
    <table class="tb-users-list">
        <thead>
            <tr>
                <?php foreach ($this->users as $key => $val) : ?> 
                <th>
                    <?= $key; ?>
                </th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <?php foreach ($this->users as $key => $val) : ?>
                <td>
                    <?php
                    echo ($key == 'user_password')
                            ? str_repeat('*', 14)
                            : $val ;
                    ?>
                </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
    <?php
    // */
    ?>
</div>

<br /><br /><br /><br />
