<?php echo $this->doctype() . PHP_EOL; ?>
<html>
<head>
    <?php
    $this->headMeta()->setCharset('UTF-8');
    $this->headLink()->setStylesheet('/css/reset.css')
                     ->appendStylesheet('/css/default.css')
                     ->appendStylesheet('/css/smoothness/jquery-ui-1.9.1.custom.css');
    $this->headScript()->setFile('/js/library/jquery-1.8.2.js')
                       ->appendFile('/js/library/jquery-ui-1.9.1.custom.min.js')
                       ->appendFile('/js/library/jquery.balloon.min.js')
                       ->appendFile('/js/myJquery.js');
    echo $this->headTitle('BUGS ME | Créations 2C') . PHP_EOL;
    echo $this->headMeta() . PHP_EOL;
    echo $this->headLink() . PHP_EOL;
    echo $this->headStyle() . PHP_EOL;
    echo $this->headScript() . PHP_EOL;
    ?>
    
</head>
<body>
    
    <div id="header">
        <div id="header-top">
            <h1 id="sitename">
                <a href="/index/index">BUGS2ME | Créations 2C</a>
            </h1> 
        </div>
        <div id="nav">
            <div id="nav-content">
                <div id="user-links" class="balloon" title="balloon content">
                    User Name (user links)
                </div>
                <?php echo $this->navigation(); ?>
                <div class="clear-both"></div>
            </div>
        </div>
    </div>
    
    <div id="notification"></div>
    
    <div id="main">
        <?php echo $this->layout()->content . PHP_EOL;?>
    </div>

    <div id="footer">
        <p style="margin-: auto; width: 1000px;">
             <img src="/img/icons_svg/b_c2c.svg" alt="Une création 2C" style="width: 24px;" />
             &nbsp;&nbsp;
             <img src="/img/PoweredBy_ZF_4LightBG.png" alt="Powered by Zend Framework" />
        </p>
    </div>
    <div id="popup">
        <div style="height: 500px">
            <h1 class="h1-page-title">HELP</h1>
            <p>
                CONTENT
                <br />
            </p>
            <p>
                <br />
                @TODO: Ajax Treatment...
            </p>
        </div>
        <div id="popup-close-btn">
            <a href="">CLOSE</a>
        </div>
    </div>
</body>
<?php //echo $this->headScript()->setFile('/js/myPrototype.js') . PHP_EOL;?>
</html>