<table class="tb-to-project-links">
    <tr>
        <td class="td-to-project-link-a">
            <img src="/img/icons_svg/w_folder_icon.svg"
                 style="width: 22px;"  />
        </td>
        <td class="td-to-project-link-b" style="font-size: 12px;">
            <a class="add-links"
               href="/project/project/0"
               style="color: #ffffff; font-size: 12px;">
                <?= $this->translate('CREATE_NEW_PROJECT'); ?>
            </a>
        </td>
    </tr>
</table>

<br />
<div class="article">
    <ul class="ul-projects">
    <?php
        $i = 0;
        foreach ($this->projects as $projectValue) :
    ?>
        <li class="li-projects">
            <table style="width: 100%">
                <tr>
                    <td style="width: 60%;">
                        <?='<a href="/project/project/'
                                        .$projectValue->getProjectId().'" 
                                 id="a-project-'
                                        .$projectValue->getProjectId().'">'
                                        . $projectValue->getProjectTitle()
                                        .'</a>'?>
                    </td>
                    <td style="width: 15%; border-left: 1px solid #ececec; padding-left: 6px;">
                        <?php
                        echo $this->translate('PROJECT_START_DATE') . ' : ';
                        echo $projectValue->getProjectStart();
                        ?>
                    </td>
                    <td style="width: 15%; border-left: 1px solid #ececec; padding-left: 6px;">
                        <?php
                        echo $this->translate('PROJECT_END_DATE') . ' : ';
                        echo $projectValue->getProjectEnd();
                        ?>
                    </td>
                </tr>
            </table>
        </li>
    <?php
    $i++;
    endforeach;
    ?>
    </ul>
</div>