<h1><?= $this->pageTitle; ?></h1>
<div class="article">
    <p style="text-align: right">
        <a class="button" href="/project/project">CREATE_NEW_PROJECT</a>
    </p>
</div>
<br /><br />
<div class="article">
    <ul class="ul-projects">
    <?php foreach ($this->projects as $projectId => $projectValue) : ?>
        <li>
        <?='<a href="" id="a-project-'.$projectId.'">'.$projectValue.'</a>'?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>