<table class="tb-projects-header"
       style="padding: 0px; margin: 0px; width: 100%;">
    <tr>
        <td style="width: 83%; text-align: left; vertical-align: bottom;">
            <?php /* ?>
            <a href="/project/project/<?= $project->getProjectId() ?>"
               style="font-size: 1.2em; font-weight: bold;">
                (#<?= $project->getProjectId() ?>)&nbsp;    
                <?php
                    echo (strlen($project->getProjectTitle()) > 30)
                            ? substr($project->getProjectTitle(), 0, 30)
                                . '...'
                            : $project->getProjectTitle();
                ?>
            </a>
            
            <?php // */ ?>
        </td>
        <td> <!-- style="padding: 0px;"-->
            <table class="tb-to-project-links"> <!--  style="padding: 0px; width: 100%;"-->
                 <tr>
                     <td class="td-to-project-link-a">
                         <img src="/img/icons_svg/w_folder_icon.svg"
                              style="height: 24px;"  />
                     </td>
                     <td class="td-to-project-link-b" 
                         style="font-size: 12px;">
                         <a class="create"
                            href="/project/create" 
                            style="color: #ffffff; font-size: 12px;">
                             <?=$this->translate('CREATE_NEW_PROJECT');?>
                         </a>
                     </td>
                 </tr>
             </table>
        </td>
    </tr>
</table>
<table class="tb-projects" style="">
    <tr>
        <th>Project Label</th>
        <th><?php echo $this->translate('PROJECT_START_DATE') ?></th>
        <th><?php echo $this->translate('PROJECT_END_DATE') ?></th>
        <th>Status</th>
    </tr>
<?php
//$project = new Project_Model_Project();
foreach ($this->projects as $project) :
    $startDate = new Zend_Date($project->getProjectStart());
    $endDate   = new Zend_Date($project->getProjectEnd());
    ?>
    <tr>
        <td style="width: 76%;">
            <?php
            echo '<a href="/project/project/' . $project->getProjectId() 
                                   . '" 
                     id="a-project-' . $project->getProjectId()
                                  . '">'
                                  . $project->getProjectTitle()
                                  . '</a>'
            ?>
        </td>
        <td style="width: 10%;">
            <?php
//            echo $this->translate('TASK_CREATE_DATE') . ' ';
            echo '<span style="color: #49A0DF">'
                . $startDate->toString('dd-MM-Y')
                . '</span>';
            ?>
        </td>
        <td style="width: 10%;">
            <?php
            echo '<span style="color: orange">'
                . $endDate->toString('dd-MM-Y')
                . '</span>';
            ?>
        </td>
        <td style="width: 4%; text-align: center;">
            <!--<img src="/img/state_medium.png"--> 

            <?php
            date_default_timezone_set('Europe/Paris');
            Zend_Date::setOptions(array('format_type' => 'php'));
//            $dateNow = Zend_Date::now("fr");
            $dateNow = new Zend_date("fr");
//            if ($dateNow->compare($endDate->getDayOfYear(), $dateNow->getDayOfYear()) == 1) {
            if ($dateNow->compare($endDate, $dateNow) == 1) {
                $imgStatus = "state_high";
            } else {
                $imgStatus = "state_low";
            }
//            echo (1 == 1) ? "state_low" : "state_high";
            ?>
            <img src="/img/<?php echo $imgStatus ?>.png"
                 alt="state low"
                 title="<?php echo $endDate . ' | ' . $dateNow ?>"
                 style="width: 12px;" />
        </td>
    </tr>
    <?php
endforeach;
?>
</table>